services:
  - type: web
    name: genai-django-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn UseEx.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: your_project_name.settings
